name: Sync Fork

on:
  push:
    branches:
      - "sync-fork"
  schedule:
    - cron: '*/30 * * * *' #every 24h
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your forked repository
        uses: actions/checkout@v4
        with:
          repository: Eurocontrol-SebastienBarbereau/atmseminar-org.github.io
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/atmseminar-org/atmseminar-org.github.io.git
          git fetch upstream

      - name: Sync with upstream/main
        run: |
          git fetch upstream master
          git checkout -B main origin/master
          git merge upstream/master
          git push origin master

      - name: Clean up
        run: |
          git remote remove upstream
